# Generated by Django 3.1.5 on 2021-01-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='third_link',
            field=models.URLField(blank=True),
        ),
    ]
