# Generated by Django 3.1.5 on 2021-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0002_auto_20210115_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='first_price',
        ),
        migrations.AddField(
            model_name='product',
            name='second_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='third_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
