# Generated by Django 3.1.5 on 2021-01-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0003_auto_20210115_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
