# Generated by Django 3.1.5 on 2021-01-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0004_auto_20210115_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='third_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='third_price',
        ),
    ]
